export interface Lesson {
  id: string;
  number: number;
  title: string;
  type: "keys" | "review" | "practice" | "game";
  status: "completed" | "in-progress" | "locked";
}

export interface Stage {
  id: string;
  title: string;
  lessons: Lesson[];
}

export const STAGES: Stage[] = [
  {
    id: "stage-1",
    title: "Fileira Principal",
    lessons: [
      {
        id: "l1",
        number: 1,
        title: "Intro à Digitação",
        type: "game",
        status: "completed",
      },
      {
        id: "l2",
        number: 2,
        title: "Teclas f & j",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l3",
        number: 3,
        title: "Rever: f & j",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l4",
        number: 4,
        title: "Praticar: f & j",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l5",
        number: 5,
        title: "Teclas d & k",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l6",
        number: 6,
        title: "Rever: d & k",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l7",
        number: 7,
        title: "Praticar: d & k",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l8",
        number: 8,
        title: "Teclas s & l",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l9",
        number: 9,
        title: "Rever: s & l",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l10",
        number: 10,
        title: "Praticar: s & l",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l11",
        number: 11,
        title: "Teclas a & ;",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l12",
        number: 12,
        title: "Rever: a & ;",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l13",
        number: 13,
        title: "Praticar: a & ;",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l14",
        number: 14,
        title: "Teclas g & h",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l15",
        number: 15,
        title: "Rever: g & h",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l16",
        number: 16,
        title: "Praticar: g & h",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l17",
        number: 17,
        title: "Jogar: Principal",
        type: "game",
        status: "in-progress",
      },
      {
        id: "l18",
        number: 18,
        title: "Revisão: Principal",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l19",
        number: 19,
        title: "Praticar: Completo",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l20",
        number: 20,
        title: "Desafio: Principal",
        type: "game",
        status: "in-progress",
      },
    ],
  },
  {
    id: "stage-2",
    title: "Fileira Superior",
    lessons: [
      {
        id: "l21",
        number: 21,
        title: "Teclas r & u",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l22",
        number: 22,
        title: "Rever: r & u",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l23",
        number: 23,
        title: "Praticar: r & u",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l24",
        number: 24,
        title: "Teclas e & i",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l25",
        number: 25,
        title: "Rever: e & i",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l26",
        number: 26,
        title: "Praticar: e & i",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l27",
        number: 27,
        title: "Teclas w & o",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l28",
        number: 28,
        title: "Rever: w & o",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l29",
        number: 29,
        title: "Praticar: w & o",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l30",
        number: 30,
        title: "Teclas q & y",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l31",
        number: 31,
        title: "Rever: q & y",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l32",
        number: 32,
        title: "Praticar: q & y",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l33",
        number: 33,
        title: "Teclas t & p",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l34",
        number: 34,
        title: "Rever: t & p",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l35",
        number: 35,
        title: "Praticar: t & p",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l36",
        number: 36,
        title: "Jogar: Superior",
        type: "game",
        status: "in-progress",
      },
      {
        id: "l37",
        number: 37,
        title: "Revisão: Superior",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l38",
        number: 38,
        title: "Praticar: Todas",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l39",
        number: 39,
        title: "Desafio: Híbrido",
        type: "game",
        status: "in-progress",
      },
      {
        id: "l40",
        number: 40,
        title: "Velocidade: Fileiras",
        type: "practice",
        status: "in-progress",
      },
    ],
  },
  {
    id: "stage-3",
    title: "Fileira Inferior & Pontuação",
    lessons: [
      {
        id: "l41",
        number: 41,
        title: "Teclas z & /",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l42",
        number: 42,
        title: "Rever: z & /",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l43",
        number: 43,
        title: "Praticar: z & /",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l44",
        number: 44,
        title: "Teclas x & .",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l45",
        number: 45,
        title: "Rever: x & .",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l46",
        number: 46,
        title: "Praticar: x & .",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l47",
        number: 47,
        title: "Teclas c & ,",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l48",
        number: 48,
        title: "Rever: c & ,",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l49",
        number: 49,
        title: "Praticar: c & ,",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l50",
        number: 50,
        title: "Teclas v & m",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l51",
        number: 51,
        title: "Rever: v & m",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l52",
        number: 52,
        title: "Praticar: v & m",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l53",
        number: 53,
        title: "Teclas b & n",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l54",
        number: 54,
        title: "Rever: b & n",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l55",
        number: 55,
        title: "Praticar: b & n",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l56",
        number: 56,
        title: "Jogar: Inferior",
        type: "game",
        status: "in-progress",
      },
      {
        id: "l57",
        number: 57,
        title: "Revisão: Todas Letras",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l58",
        number: 58,
        title: "Praticar: Todas as Letras",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l59",
        number: 59,
        title: "Desafio: Letras Completo",
        type: "game",
        status: "in-progress",
      },
      {
        id: "l60",
        number: 60,
        title: "Velocidade: Mestre em Letras",
        type: "practice",
        status: "in-progress",
      },
    ],
  },
  {
    id: "stage-4",
    title: "Caracteres Especiais & Números",
    lessons: [
      {
        id: "l61",
        number: 61,
        title: "Teclas [ & ]",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l62",
        number: 62,
        title: "Rever: [ & ]",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l63",
        number: 63,
        title: "Praticar: [ & ]",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l64",
        number: 64,
        title: "Teclas ; & '",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l65",
        number: 65,
        title: "Rever: ; & '",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l66",
        number: 66,
        title: "Praticar: ; & '",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l67",
        number: 67,
        title: "Tecla \\ & |",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l68",
        number: 68,
        title: "Rever: \\ & |",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l69",
        number: 69,
        title: "Praticar: \\ & |",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l70",
        number: 70,
        title: "Números 1-5",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l71",
        number: 71,
        title: "Rever: 1-5",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l72",
        number: 72,
        title: "Praticar: 1-5",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l73",
        number: 73,
        title: "Números 6-0",
        type: "keys",
        status: "in-progress",
      },
      {
        id: "l74",
        number: 74,
        title: "Rever: 6-0",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l75",
        number: 75,
        title: "Praticar: 6-0",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l76",
        number: 76,
        title: "Jogar: Especiais",
        type: "game",
        status: "in-progress",
      },
      {
        id: "l77",
        number: 77,
        title: "Revisão: Especiais",
        type: "review",
        status: "in-progress",
      },
      {
        id: "l78",
        number: 78,
        title: "Praticar: Tudo",
        type: "practice",
        status: "in-progress",
      },
      {
        id: "l79",
        number: 79,
        title: "Desafio: Final",
        type: "game",
        status: "in-progress",
      },
      {
        id: "l80",
        number: 80,
        title: "Velocidade: Mestre",
        type: "practice",
        status: "in-progress",
      },
    ],
  },
];