export const typingArenaLabels = {
  pt: {
    wpm: "VPD",
    errors: "ERROS",
    remaining: "RESTANTES",
    consecutiveErrors: "ERROS SEGUIDOS",
    initializingArena: "Inicializando Arena...",
    submittingResult: "Enviando Resultado...",
    invalidSession: "Sessão Inválida",
    sessionNotFound: "A sessão que procuras não existe ou expirou.",
    backToSelection: "Voltar para Seleção",
    errorSubmitting: "Erro ao submeter sessão",
    // Learn Practice labels
    introductionNewKey: "INTRODUÇÃO À NOVA TECLA",
    typingPractice: "PRÁTICA DE DIGITAÇÃO",
    lesson: "LIÇÃO",
    practiceKeys: "Pratique as teclas",
  },
  en: {
    wpm: "WPM",
    errors: "ERRORS",
    remaining: "REMAINING",
    consecutiveErrors: "CONSECUTIVE ERRORS",
    initializingArena: "Initializing Arena...",
    submittingResult: "Submitting Result...",
    invalidSession: "Invalid Session",
    sessionNotFound: "The session you are looking for does not exist or has expired.",
    backToSelection: "Back to Selection",
    errorSubmitting: "Error submitting session",
    // Learn Practice labels
    introductionNewKey: "INTRODUCTION TO NEW KEY",
    typingPractice: "TYPING PRACTICE",
    lesson: "LESSON",
    practiceKeys: "Practice the keys",
  },
  fr: {
    wpm: "VPM",
    errors: "ERREURS",
    remaining: "RESTANT",
    consecutiveErrors: "ERREURS CONSÉCUTIVES",
    initializingArena: "Initialisation de l'Arène...",
    submittingResult: "Envoi du Résultat...",
    invalidSession: "Session Invalide",
    sessionNotFound: "La session que vous recherchez n'existe pas ou a expiré.",
    backToSelection: "Retour à la Sélection",
    errorSubmitting: "Erreur lors de l'envoi de la session",
    // Learn Practice labels
    introductionNewKey: "INTRODUCTION À LA NOUVELLE TOUCHE",
    typingPractice: "PRATIQUE DE DACTYLOGRAPHIE",
    lesson: "LEÇON",
    practiceKeys: "Pratiquez les touches",
  },
};
