export const channelViewLabelsByLocale = {
  pt: {
    official: "Oficial",
    edited: "editado",
    empty: "Sem mensagens ainda",
    emptyHint: "Se o primeiro a escrever em",
    readOnly: "Tens permissao apenas de leitura neste canal",
    updatesOnly: "Canal apenas para novidades da plataforma",
    messagePlaceholder: "Mensagem em",
    attachFiles: "Anexar ficheiros",
    attachmentsOnly: "Ficheiros anexados",
    pickEmoji: "Escolher emoji",
    addReaction: "Adicionar reacao",
    editMessage: "Editar",
    deleteMessage: "Apagar",
    save: "Guardar",
    cancel: "Cancelar",
    confirmDelete: "Queres apagar esta mensagem?",
  },
  en: {
    official: "Official",
    edited: "edited",
    empty: "No messages yet",
    emptyHint: "Be the first to write in",
    readOnly: "You only have read permission in this channel",
    updatesOnly: "This channel is only for platform updates",
    messagePlaceholder: "Message in",
    attachFiles: "Attach files",
    attachmentsOnly: "Files attached",
    pickEmoji: "Pick emoji",
    addReaction: "Add reaction",
    editMessage: "Edit",
    deleteMessage: "Delete",
    save: "Save",
    cancel: "Cancel",
    confirmDelete: "Do you want to delete this message?",
  },
  fr: {
    official: "Officiel",
    edited: "modifie",
    empty: "Aucun message pour le moment",
    emptyHint: "Soyez le premier a ecrire dans",
    readOnly: "Vous avez uniquement un acces en lecture dans ce canal",
    updatesOnly: "Canal reserve aux nouveautes de la plateforme",
    messagePlaceholder: "Message dans",
    attachFiles: "Joindre des fichiers",
    attachmentsOnly: "Fichiers joints",
    pickEmoji: "Choisir un emoji",
    addReaction: "Ajouter une reaction",
    editMessage: "Modifier",
    deleteMessage: "Supprimer",
    save: "Enregistrer",
    cancel: "Annuler",
    confirmDelete: "Voulez-vous supprimer ce message ?",
  },
} as const;

export const channelViewEmojiGroups = [
  [
    "😀", "😁", "😂", "🤣", "😅", "😊", "🙂", "😉",
    "😄", "😆", "😋", "😌", "🙃", "😇", "🥳", "🤩",
  ],
  [
    "😍", "😘", "😎", "🤓", "🤯", "😴", "🙌", "👏",
    "🥰", "😏", "🤗", "🫡", "😺", "😹", "😻", "🤠",
  ],
  [
    "🔥", "💯", "🚀", "🎉", "✅", "❌", "🤝", "🧠",
    "⚡", "🌟", "💥", "🎯", "🏆", "💎", "🛡️", "📈",
  ],
  [
    "🍕", "🍔", "🍟", "🌮", "🍩", "☕", "🍓", "🍉",
    "🍜", "🍣", "🥤", "🧋", "🍰", "🍪", "🥑", "🌽",
  ],
  [
    "🐶", "🐱", "🦊", "🐼", "🐸", "🦁", "🐨", "🐯",
    "🐵", "🐧", "🦄", "🐙", "🐢", "🦖", "🐬", "🦋",
  ],
  [
    "⚽", "🏀", "🏈", "⚾", "🎾", "🏐", "🥊", "🏓",
    "🏸", "⛳", "🎳", "🛹", "🏄", "🚴", "🏋️", "🤸",
  ],
  [
    "💻", "📱", "⌨️", "🖥️", "🕹️", "🎧", "📷", "📡",
    "🔋", "🧩", "🛜", "🛰️", "🤖", "🧪", "⚙️", "🔧",
  ],
  [
    "🌍", "🌙", "⭐", "☀️", "🌈", "⛈️", "❄️", "🌊",
    "🌴", "🌸", "🍁", "🏔️", "🌋", "🪐", "🌌", "🌠",
  ],
] as const;
