export const communitySidebarLabelsByLocale = {
  pt: {
    community: "Comunidade",
    platform: "Plataforma",
    myGroups: "Os meus grupos",
    createGroup: "Criar grupo",
    noGroups: "Nenhum grupo ainda",
    directMessages: "Mensagens directas",
    pendingInvites: "Convites pendentes",
    inviteMembers: "Convidar membros",
    acceptInvite: "Aceitar",
    noInvites: "Sem convites pendentes",
    loadingInvites: "A carregar convites...",
    addFriends: "Adicionar amigos",
    search: "Pesquisar",
    searchPlaceholder: "Pesquisar utilizadores para iniciar DM...",
    users: "Utilizadores",
    searchingUsers: "A procurar utilizadores...",
    noUsersFound: "Nenhum utilizador encontrado",
    openDm: "Abrir DM",
    startDm: "Iniciar DM",
    noResults: "Sem resultados",
    online: "Online",
    rejectInvite: "Recusar",
    close: "Fechar",
  },
  en: {
    community: "Community",
    platform: "Platform",
    myGroups: "My groups",
    createGroup: "Create group",
    noGroups: "No groups yet",
    directMessages: "Direct messages",
    pendingInvites: "Pending invites",
    inviteMembers: "Invite members",
    acceptInvite: "Accept",
    noInvites: "No pending invites",
    loadingInvites: "Loading invites...",
    addFriends: "Add friends",
    search: "Search",
    searchPlaceholder: "Search users to start a DM...",
    users: "Users",
    searchingUsers: "Searching users...",
    noUsersFound: "No users found",
    openDm: "Open DM",
    startDm: "Start DM",
    noResults: "No results",
    online: "Online",
    rejectInvite: "Decline",
    close: "Close",
  },
  fr: {
    community: "Communaute",
    platform: "Plateforme",
    myGroups: "Mes groupes",
    createGroup: "Creer un groupe",
    noGroups: "Aucun groupe pour l'instant",
    directMessages: "Messages directs",
    pendingInvites: "Invitations en attente",
    inviteMembers: "Inviter des membres",
    acceptInvite: "Accepter",
    noInvites: "Aucune invitation en attente",
    loadingInvites: "Chargement des invitations...",
    addFriends: "Ajouter des amis",
    search: "Rechercher",
    searchPlaceholder: "Rechercher des utilisateurs pour lancer un DM...",
    users: "Utilisateurs",
    searchingUsers: "Recherche d'utilisateurs...",
    noUsersFound: "Aucun utilisateur trouve",
    openDm: "Ouvrir DM",
    startDm: "Demarrer DM",
    noResults: "Aucun resultat",
    online: "En ligne",
    rejectInvite: "Refuser",
    close: "Fermer",
  },
} as const;
