export const createGroupLabelsByLocale = {
  pt: {
    title: "Criar grupo privado",
    subtitle: "Os grupos publicos sao geridos pela plataforma",
    nameLabel: "Nome do grupo *",
    namePlaceholder: "Ex: Algo Masters",
    descriptionLabel: "Descricao",
    descriptionPlaceholder: "O que e este grupo?",
    privateInfoPrefix: "Grupos privados sao ",
    privateInfoSuffix: ". So membros podem ver as mensagens.",
    inviteOnly: "por convite",
    cancel: "Cancelar",
    create: "Criar grupo",
    creating: "A criar...",
  },
  en: {
    title: "Create private group",
    subtitle: "Public groups are managed by the platform",
    nameLabel: "Group name *",
    namePlaceholder: "Ex: Algo Masters",
    descriptionLabel: "Description",
    descriptionPlaceholder: "What is this group about?",
    privateInfoPrefix: "Private groups are ",
    privateInfoSuffix: ". Only members can see the messages.",
    inviteOnly: "invite-only",
    cancel: "Cancel",
    create: "Create group",
    creating: "Creating...",
  },
  fr: {
    title: "Creer un groupe prive",
    subtitle: "Les groupes publics sont geres par la plateforme",
    nameLabel: "Nom du groupe *",
    namePlaceholder: "Ex : Algo Masters",
    descriptionLabel: "Description",
    descriptionPlaceholder: "De quoi s'agit-il ?",
    privateInfoPrefix: "Les groupes prives sont ",
    privateInfoSuffix: ". Seuls les membres peuvent voir les messages.",
    inviteOnly: "sur invitation uniquement",
    cancel: "Annuler",
    create: "Creer le groupe",
    creating: "Creation...",
  },
} as const;
