export const editGroupLabelsByLocale = {
  pt: {
    title: "Editar Grupo",
    subtitle: "Modifica os detalhes do teu canal privado",
    nameLabel: "Nome do Grupo",
    namePlaceholder: "Introduz o novo nome...",
    descriptionLabel: "Descrição (Opcional)",
    descriptionPlaceholder: "Sobre o que é este grupo?",
    cancel: "Cancelar",
    save: "Guardar Alterações",
    delete: "Remover Grupo",
    deleteConfirm: "Tens a certeza que queres remover este grupo? Esta ação não pode ser desfeita.",
    saving: "A guardar...",
  },
  en: {
    title: "Edit Group",
    subtitle: "Modify your private channel details",
    nameLabel: "Group Name",
    namePlaceholder: "Enter new name...",
    descriptionLabel: "Description (Optional)",
    descriptionPlaceholder: "What is this group about?",
    cancel: "Cancel",
    save: "Save Changes",
    delete: "Remove Group",
    deleteConfirm: "Are you sure you want to remove this group? This action cannot be undone.",
    saving: "Saving...",
  },
  fr: {
    title: "Modifier le Groupe",
    subtitle: "Modifiez les détails de votre canal privé",
    nameLabel: "Nom du Groupe",
    namePlaceholder: "Entrez le nouveau nom...",
    descriptionLabel: "Description (Optionnel)",
    descriptionPlaceholder: "De quoi parle ce groupe?",
    cancel: "Annuler",
    save: "Enregistrer",
    delete: "Supprimer le Groupe",
    deleteConfirm: "Êtes-vous sûr de vouloir supprimer ce groupe? Cette action est irréversible.",
    saving: "Enregistrement...",
  },
} as const;
