export const inviteMemberLabelsByLocale = {
  pt: {
    title: "Convidar membros",
    subtitle: "para",
    shareLink: "Link de convite",
    copied: "Copiado",
    copy: "Copiar",
    inviteByUsername: "Convidar por username",
    searchPlaceholder: "Pesquisar utilizadores...",
    searching: "A pesquisar utilizadores...",
    noneFound: "Nenhum utilizador encontrado",
    inviteSelected: "Convidar selecionados",
    cancel: "Cancelar",
    sent: "Enviado!",
  },
  en: {
    title: "Invite members",
    subtitle: "to",
    shareLink: "Invite link",
    copied: "Copied",
    copy: "Copy",
    inviteByUsername: "Invite by username",
    searchPlaceholder: "Search users...",
    searching: "Searching users...",
    noneFound: "No users found",
    inviteSelected: "Invite selected",
    cancel: "Cancel",
    sent: "Sent!",
  },
  fr: {
    title: "Inviter des membres",
    subtitle: "a",
    shareLink: "Lien d'invitation",
    copied: "Copie",
    copy: "Copier",
    inviteByUsername: "Inviter par nom d'utilisateur",
    searchPlaceholder: "Rechercher des utilisateurs...",
    searching: "Recherche des utilisateurs...",
    noneFound: "Aucun utilisateur trouve",
    inviteSelected: "Inviter la selection",
    cancel: "Annuler",
    sent: "Envoye !",
  },
} as const;
