export const manageRoleLabelsByLocale = {
  pt: {
    title: "Gerir membro",
    admin: "Admin",
    adminDesc: "Pode adicionar membros e moderar mensagens",
    member: "Membro",
    memberDesc: "Pode ler e enviar mensagens",
    viewer: "Leitor",
    viewerDesc: "Apenas pode ler mensagens",
    staff: "Staff",
    owner: "Owner",
    protected: "Nao podes alterar permissoes de um Owner ou Staff.",
    changePermission: "Alterar permissao",
    current: "atual",
    remove: "Remover",
    ban: "Banir",
    sure: "Tens a certeza?",
    yes: "Sim",
    no: "Nao",
    saved: "Guardado",
    removed: "Removido",
    banned: "Banido",
    save: "Guardar",
  },
  en: {
    title: "Manage member",
    admin: "Admin",
    adminDesc: "Can add members and moderate messages",
    member: "Member",
    memberDesc: "Can read and send messages",
    viewer: "Viewer",
    viewerDesc: "Can only read messages",
    staff: "Staff",
    owner: "Owner",
    protected: "You cannot change permissions for an Owner or Staff member.",
    changePermission: "Change permission",
    current: "current",
    remove: "Remove",
    ban: "Ban",
    sure: "Are you sure?",
    yes: "Yes",
    no: "No",
    saved: "Saved",
    removed: "Removed",
    banned: "Banned",
    save: "Save",
  },
  fr: {
    title: "Gerer le membre",
    admin: "Admin",
    adminDesc: "Peut ajouter des membres et moderer les messages",
    member: "Membre",
    memberDesc: "Peut lire et envoyer des messages",
    viewer: "Lecteur",
    viewerDesc: "Peut seulement lire les messages",
    staff: "Staff",
    owner: "Owner",
    protected: "Vous ne pouvez pas modifier les permissions d'un Owner ou d'un Staff.",
    changePermission: "Modifier la permission",
    current: "actuel",
    remove: "Retirer",
    ban: "Bannir",
    sure: "Etes-vous sur ?",
    yes: "Oui",
    no: "Non",
    saved: "Enregistre",
    removed: "Retire",
    banned: "Banni",
    save: "Enregistrer",
  },
} as const;
