export const memberPanelLabelsByLocale = {
  pt: {
    managePermissions: "Gerir permissoes",
    members: "membros",
    activeMembers: "ativos",
    membersVisible: "membros visiveis",
    partialListHint: "Lista parcial ate haver mais atividade no canal.",
    online: "Online",
    away: "Ausente",
    offline: "Offline",
    none: "Nenhum membro",
    legend: "Legenda",
    owner: "Owner",
    admin: "Admin",
    member: "Membro",
    viewer: "Leitor",
    editChannel: "Editar Canal",
  },
  en: {
    managePermissions: "Manage permissions",
    members: "members",
    activeMembers: "active",
    membersVisible: "members visible",
    partialListHint: "Partial list until there is more channel activity.",
    online: "Online",
    away: "Away",
    offline: "Offline",
    none: "No members",
    legend: "Legend",
    owner: "Owner",
    admin: "Admin",
    member: "Member",
    viewer: "Viewer",
    editChannel: "Edit Channel",
  },
  fr: {
    managePermissions: "Gerer les permissions",
    members: "membres",
    activeMembers: "actifs",
    membersVisible: "membres visibles",
    partialListHint: "Liste partielle jusqu'a plus d'activite dans le canal.",
    online: "En ligne",
    away: "Absent",
    offline: "Hors ligne",
    none: "Aucun membre",
    legend: "Legende",
    owner: "Owner",
    admin: "Admin",
    member: "Membre",
    viewer: "Lecteur",
    editChannel: "Modifier le canal",
  },
} as const;
