export const labelsByLocale = {
  pt: {
    official: "Oficial",
    casual: "Casual",
    organizedBy: "Organizado por:",
    start: "Início:",
    description: "Descrição",
    rulesFormat: "Regras e Formato",
    winCriteria: "Critério de Vitória",
    winTyping: "Velocidade (WPM) com precisão mínima de 95%.",
    winCp: "Problemas resolvidos + tempo (vence o mais rápido no empate).",
    globalRanking: "Ranking Global",
    globalPublic: "Impacto direto no teu rank de módulo e perfil público.",
    globalPrivate: "Resultado local — apenas visível para participantes.",
    submissionPipeline: "Pipeline de Submissão",
    submissionTyping: "Correção em tempo real. Erros bloqueiam o progresso.",
    submissionCp: "Progressão de testes mostrada em tempo real.",
    penalties: "Penalizações",
    penaltiesDesc:
      "Qualquer forma de automação ou uso de scripts resultará em DQ imediata.",
    lobbyActive: "Lobby ativo",
    joinEvent: "Juntar-se ao evento",
    enterArena: "Entrar no Arena",
    joinNotice:
      "Ao entrares, concordas com as regras do evento e o código de conduta do NT.",
    ready: "Pronto!",
    getReady: "Preparar (Ready)",
    autoStart: "Inicia automaticamente em breve",
    lobbyChatActive: "Chat do Lobby ativo...",
    inviteParticipants: "Convidar Participantes",
    inviteEmailPlaceholder: "email@escola42.com",
    inviteButton: "Convidar",
    startEvent: "Iniciar Evento",
    rounds: "Rondas do Evento",
    acceptInvite: "Aceitar Convite",
    back: "Voltar aos Eventos",
    fullRanking: "Ranking Completo",
    officialResults: "Resultados Oficiais",
    arenaStats: "Estatísticas Arena",
    overview: "Contexto Geral",
    rank: "Rank",
    programmer: "Programador",
    score: "Score",
    time: "Tempo",
    xp: "XP",
    restartEvent: "Reiniciar Evento",
    featureInProgress: "Funcionalidade em desenvolvimento",
    syncingRankings: "Sincronizando Rankings...",
    errorEventNotFound: "Erro: Dados do evento não encontrados.",
    restartFeatureDesc: "A funcionalidade de reiniciar evento estará disponível brevemente.",
    yourPerformance: "O Teu Desempenho",
    statusFinished: "Finalizado",
    statusUnranked: "Não classificado",
    totalScore: "Score Total",
    medal: "Medalha",
    none: "Nenhuma",
    shareArena: "Partilhar Arena",
    place: "Lugar",
    participants: "Participantes",
    inEvent: "NO EVENTO",
    pending: "PENDENTE",
    otherProgrammers: "outros programadores",
    category: "Categoria",
    difficulty: "Dificuldade",
    round: "RONDA",
    timesUp: "Tempo esgotado!",
    nextRound: "Próxima Ronda",
    wpm: "VPD",
    errors: "ERROS",
    remaining: "RESTANTES",
    you: "VOCÊ",
    loadingUser: "Carregando usuário...",
    waitingEventStart: "Aguardando início do evento...",
    waitForEventStart: "Aguarde o início do evento",
  },
  en: {
    official: "Official",
    casual: "Casual",
    organizedBy: "Organized by:",
    start: "Start:",
    description: "Description",
    rulesFormat: "Rules and Format",
    winCriteria: "Win Criteria",
    winTyping: "Speed (WPM) with minimum 95% accuracy.",
    winCp: "Problems solved + time (faster wins on tie).",
    globalRanking: "Global Ranking",
    globalPublic: "Direct impact on your module rank and public profile.",
    globalPrivate: "Local result — visible only to participants.",
    submissionPipeline: "Submission Pipeline",
    submissionTyping: "Real-time correction. Errors block progress.",
    submissionCp: "Test case progression shown in real time.",
    penalties: "Penalties",
    penaltiesDesc:
      "Any form of automation or script usage will result in immediate DQ.",
    lobbyActive: "Lobby active",
    joinEvent: "Join event",
    enterArena: "Enter Arena",
    joinNotice:
      "By joining, you agree to the event rules and the NT code of conduct.",
    ready: "Ready!",
    getReady: "Get Ready",
    autoStart: "Starts automatically soon",
    lobbyChatActive: "Lobby chat active...",
    inviteParticipants: "Invite Participants",
    inviteEmailPlaceholder: "email@school42.com",
    inviteButton: "Invite",
    startEvent: "Start Event",
    rounds: "Event Rounds",
    acceptInvite: "Accept Invite",
    back: "Back to Events",
    fullRanking: "Full Ranking",
    officialResults: "Official Results",
    arenaStats: "Arena Stats",
    overview: "Overview",
    rank: "Rank",
    programmer: "Programmer",
    score: "Score",
    time: "Time",
    xp: "XP",
    restartEvent: "Restart Event",
    featureInProgress: "Feature in progress",
    syncingRankings: "Synchronizing Rankings...",
    errorEventNotFound: "Error: Event data not found.",
    restartFeatureDesc: "The restart event feature will be available shortly.",
    yourPerformance: "Your Performance",
    statusFinished: "Finished",
    statusUnranked: "Unranked",
    totalScore: "Total Score",
    medal: "Medal",
    none: "None",
    shareArena: "Share Arena",
    place: "Place",
    participants: "Participants",
    inEvent: "IN EVENT",
    pending: "PENDING",
    otherProgrammers: "other programmers",
    category: "Category",
    difficulty: "Difficulty",
    round: "ROUND",
    timesUp: "Time's up!",
    nextRound: "Next Round",
    wpm: "WPM",
    errors: "ERRORS",
    remaining: "REMAINING",
    you: "YOU",
    loadingUser: "Loading user...",
    waitingEventStart: "Waiting for event start...",
    waitForEventStart: "Wait for event start",
  },
  fr: {
    official: "Officiel",
    casual: "Casual",
    organizedBy: "Organisé par :",
    start: "Début :",
    description: "Description",
    rulesFormat: "Règles et format",
    winCriteria: "Critère de victoire",
    winTyping: "Vitesse (WPM) com précision minimale de 95 %.",
    winCp: "Problèmes résolus + temps (le plus rápido gagne en cas d'égalité).",
    globalRanking: "Classement global",
    globalPublic:
      "Impact direct sur votre rang de module et votre profil public.",
    globalPrivate: "Résultat local — visible uniquement par les participants.",
    submissionPipeline: "Pipeline de soumission",
    submissionTyping:
      "Correction en tempo réel. Les erreurs bloquent la progression.",
    submissionCp: "Progression des tests affichée en tempo réel.",
    penalties: "Pénalités",
    penaltiesDesc:
      "Toute forma d'automatisation ou d'utilisation de scripts entraîne une DQ immédiate.",
    lobbyActive: "Lobby actif",
    joinEvent: "Rejoindre l'événement",
    enterArena: "Entrer dans l'arène",
    joinNotice:
      "En rejoignant, vous acceptez les règles de l'événement et le code de conduite de NT.",
    ready: "Prêt !",
    getReady: "Se preparar",
    autoStart: "Démarre automatiquement bientôt",
    lobbyChatActive: "Chat du lobby actif...",
    inviteParticipants: "Inviter des participants",
    inviteEmailPlaceholder: "email@ecole42.fr",
    inviteButton: "Inviter",
    startEvent: "Démarrer l'événement",
    rounds: "Rondes de l'événement",
    acceptInvite: "Accepter l'invitation",
    back: "Retour aux événements",
    fullRanking: "Classement complet",
    officialResults: "Résultats officiels",
    arenaStats: "Statistiques de l'arène",
    overview: "Vue d'ensemble",
    rank: "Rang",
    programmer: "Programmeur",
    score: "Score",
    time: "Temps",
    xp: "XP",
    restartEvent: "Redémarrer l'événement",
    featureInProgress: "Fonctionnalité en cours",
    syncingRankings: "Synchronisation des classements...",
    errorEventNotFound: "Erreur : Données de l'événement introuvables.",
    restartFeatureDesc: "La fonctionnalité de redémarrage de l'événement sera bientôt disponible.",
    yourPerformance: "Votre performance",
    statusFinished: "Terminé",
    statusUnranked: "Non classé",
    totalScore: "Score total",
    medal: "Médaille",
    none: "Aucune",
    shareArena: "Partager l'arène",
    place: "Place",
    participants: "participants",
    inEvent: "EN ÉVÉNEMENT",
    pending: "EN ATTENTE",
    otherProgrammers: "autres programmeurs",
    category: "Catégorie",
    difficulty: "Difficulté",
    round: "RONDE",
    timesUp: "Temps écoulé !",
    nextRound: "Ronde suivante",
    wpm: "VPM",
    errors: "ERREURS",
    remaining: "RESTANT",
    you: "VOUS",
    loadingUser: "Chargement de l'utilisateur...",
    waitingEventStart: "Attente du début de l'événement...",
    waitForEventStart: "Attendez le début de l'événement",
  },
};
