import { fr } from "date-fns/locale";
import { sub } from "date-fns/sub";
import { error } from "node:console";
import { title } from "node:process";

export const FRIENDS_LABEL = {
    pt: {
        friends: "Amigos",
        subtitle: "Gerencie seus amigos e pedidos de amizade",
        requests: "Pedidos",
        loadingFriends: "Carregando amigos...",
        errorLoadingFriends: "Erro ao carregar lista de amigos",
        noFriends: "Você ainda não tem amigos",
        friendsSince: "Amigos desde",
        removing: "Removendo...",
        remove: "Remover",
        loadingRequests: "Carregando pedidos...",
        errorLoadingRequests: "Erro ao carregar pedidos de amizade",
        noPendentsRequests: "Nenhum pedido de amizade pendente",
        accept: "Aceitar",
        reject: "Rejeitar",
        sending: "Enviando...",
        sendingRequest: "Enviar pedido...",
        cancel: "Cancelar",
        sendingRequesSuccess: "Pedido enviado com sucesso",
        noUserFound: "Nenhum usuário encontrado",
        admin: "Admin",
        informations: "Informações",
        placeholder: "Busque por email ou nome...",
        friendNotFound: "Amigo não encontrado",
    },
    en: {
        friends: "Friends",
        subtitle: "Manage your friends and friend requests",
        requests: "Requests",
        loadingFriends: "Loading friends...",
        errorLoadingFriends: "Error loading friends list",
        noFriends: "You don't have any friends yet",
        friendsSince: "Friends since",
        removing: "Removing...",
        remove: "Remove",
        loadingRequests: "Loading requests...",
        errorLoadingRequests: "Error loading friend requests",
        noPendentsRequests: "No pending friend requests",
        accept: "Accept",
        reject: "Reject",
        sending: "Sending...",
        sendingRequest: "Sending request...",
        cancel: "Cancel",
        sendingRequesSuccess: "Friend request sent successfully",
        noUserFound: "No user found",
        admin: "Admin",
        informations: "Informations",
        placeholder: "Search by email or name...",
        friendNotFound: "Friend not found",
    },
    fr: {
        friends: "Amis",
        subtitle: "Gérez vos amis et demandes d'amis",
        requests: "Demandes",
        loadingFriends: "Chargement des amis...",
        errorLoadingFriends: "Erreur lors du chargement de la liste d'amis",
        noFriends: "Vous n'avez pas encore d'amis",
        friendsSince: "Amis depuis",
        removing: "Suppression...",
        remove: "Supprimer",
        loadingRequests: "Chargement des demandes...",
        errorLoadingRequests: "Erreur lors du chargement des demandes d'amis",
        noPendentsRequests: "Aucune demande d'ami en attente",
        accept: "Accepter",
        reject: "Rejeter",
        sending: "Envoi...",
        sendingRequest: "Envoi de la demande...",
        cancel: "Annuler",
        sendingRequesSuccess: "Demande d'ami envoyée avec succès",
        noUserFound: "Aucun utilisateur trouvé",
        admin: "Admin",
        informations: "Informations",
        placeholder: "Rechercher par email ou nom...",
        friendNotFound: "Ami non trouvé",
    },
}