import { Keyboard, Trophy, BookOpen, Bug } from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const moduleIcons: Record<string, LucideIcon> = {
  typing: Keyboard,
  competitive: Trophy,
  learning: BookOpen,
  bugs: Bug,
};

export const moduleColors: Record<
  string,
  { text: string; glow: string; bar: string }
> = {
  typing: { text: "text-primary", glow: "box-glow", bar: "bg-primary" },
  competitive: {
    text: "text-[--neon-cyan]",
    glow: "box-glow-cyan",
    bar: "bg-[--neon-cyan]",
  },
  learning: {
    text: "text-[--neon-amber]",
    glow: "box-glow-amber",
    bar: "bg-[--neon-amber]",
  },
  bugs: { text: "text-destructive", glow: "", bar: "bg-destructive" },
};

export const moduleNames: Record<string, string> = {
  typing: "Typing Code",
  competitive: "Prog. Competitiva",
  learning: "Learn Programming",
  bugs: "Learning from Bugs",
};

export const PROFILE_LABELS = {
  pt: {
    // Hero
    activeSince: "Ativo desde",
    editProfile: "Editar Perfil",
    totalXp: "XP Total",
    rank: "Rank Global",
    status: "Status",
    // Sections
    moduleActivity: "Atividade de typing",
    lastSession: "Última sessão",
    accuracy: "Precisão Média",
    maxWpm: "WPM Máximo",
    nextModuleSoon: "Próximo Módulo em breve...",
    recentHistory: "Histórico Recente",
    typingSession: "Sessão de Digitação",
    noActivity: "Nenhuma atividade registrada ainda.",
    totalSessions: "Total de Sessões",
    lastActive: "Última Atividade",
    skillAnalysis: "Análise de Habilidades",
    languages: "Linguagens",
    account: "Conta",
    role: "Role",
    visibility: "Visibilidade",
    typingSpeed: "Velocidade de Escrita",
    statistics: "Estatísticas",
    completed: "Concluído",
    public: "Público",
    radarTyping: "Digitação",
    radarCompetitive: "Competitivo",
    radarLearning: "Aprendizado",
    radarBugs: "Bugs",
    radarSpeed: "Velocidade",
    radarAccuracy: "Precisão",
    // Modal
    updateProtocol: "Profile_Update_Protocol.sh",
    username: "Nome de Utilizador",
    avatarUrl: "URL do Avatar",
    countryCode: "Código País (ISO 2)",
    bio: "Biografia",
    socialLinks: "Links Sociais",
    add: "ADICIONAR",
    cancel: "CANCELAR",
    saveChanges: "GUARDAR ALTERAÇÕES",
    processing: "PROCESSANDO...",
    success: "Perfil atualizado com sucesso!",
    error: "Erro ao atualizar perfil: ",
    bioPlaceholder: "Conte-nos um pouco sobre você...",
    uploading: "A enviar imagem...",
    clickToUpload: "Clica para fazer upload"
  },
  en: {
    // Hero
    activeSince: "Active since",
    editProfile: "Edit Profile",
    totalXp: "Total XP",
    rank: "Global Rank",
    status: "Status",
    // Sections
    moduleActivity: "Typing Activity",
    lastSession: "Last session",
    accuracy: "Average Accuracy",
    maxWpm: "Max WPM",
    nextModuleSoon: "Next Module coming soon...",
    recentHistory: "Recent History",
    typingSession: "Typing Session",
    noActivity: "No activity recorded yet.",
    totalSessions: "Total Sessions",
    lastActive: "Last Active",
    skillAnalysis: "Skill Analysis",
    languages: "Languages",
    account: "Account",
    role: "Role",
    visibility: "Visibility",
    typingSpeed: "Typing Speed",
    statistics: "Statistics",
    completed: "Completed",
    public: "Public",
    radarTyping: "Typing",
    radarCompetitive: "Competitive",
    radarLearning: "Learning",
    radarBugs: "Bugs",
    radarSpeed: "Speed",
    radarAccuracy: "Accuracy",
    // Modal
    updateProtocol: "Profile_Update_Protocol.sh",
    username: "Username",
    avatarUrl: "Avatar URL",
    countryCode: "Country Code (ISO 2)",
    bio: "Bio",
    socialLinks: "Social Links",
    add: "ADD",
    cancel: "CANCEL",
    saveChanges: "SAVE CHANGES",
    processing: "PROCESSING...",
    success: "Profile updated successfully!",
    error: "Error updating profile: ",
    bioPlaceholder: "Tell us a bit about yourself...",
    uploading: "Uploading image...",
    clickToUpload: "Click to upload"
  },
  fr: {
    // Hero
    activeSince: "Actif depuis",
    editProfile: "Modifier le profil",
    totalXp: "XP Total",
    rank: "Rang Global",
    status: "Statut",
    // Sections
    moduleActivity: "Activité de Dactylographie",
    lastSession: "Dernière session",
    accuracy: "Précision Moyenne",
    maxWpm: "WPM Maximum",
    nextModuleSoon: "Prochain Module bientôt...",
    recentHistory: "Historique Récent",
    typingSession: "Session de Dactylographie",
    noActivity: "Aucune activité enregistrée.",
    totalSessions: "Total de Sessions",
    lastActive: "Dernière Activité",
    skillAnalysis: "Analyse des Compétences",
    languages: "Langues",
    account: "Compte",
    role: "Rôle",
    visibility: "Visibilité",
    typingSpeed: "Vitesse de Frappe",
    statistics: "Statistiques",
    completed: "Terminé",
    public: "Public",
    radarTyping: "Dactylo",
    radarCompetitive: "Compétition",
    radarLearning: "Apprentissage",
    radarBugs: "Bugs",
    radarSpeed: "Vitesse",
    radarAccuracy: "Précision",
    // Modal
    updateProtocol: "Profile_Update_Protocol.sh",
    username: "Nom d'utilisateur",
    avatarUrl: "URL de l'avatar",
    countryCode: "Code Pays (ISO 2)",
    bio: "Biographie",
    socialLinks: "Liens Sociaux",
    add: "AJOUTER",
    cancel: "ANNULER",
    saveChanges: "ENREGISTRER",
    processing: "TRAITEMENT...",
    success: "Profil mis à jour avec succès !",
    error: "Erreur lors de la mise à jour : ",
    bioPlaceholder: "Parlez-nous un peu de vous...",
    uploading: "Envoi de l'image...",
    clickToUpload: "Cliquez pour importer"
  }
} as const;

export const EVENTS_LABELS = {
  pt: {
    events: "Eventos",
    wins: "Vitórias",
    totalXp: "Total XP",
    currentRank: "Rank Atual",
    trophyShelf: "Estante de Troféus",
    trophiesCollected: "2 / 10 Coletados",
    medalsCollection: "Coleção de Medalhas",
    medalsActive: "4 / 24 Ativos",
    history: "Histórico de Eventos",
    seeAll: "Ver tudo",
  },
  en: {
    events: "Events",
    wins: "Wins",
    totalXp: "Total XP",
    currentRank: "Current Rank",
    trophyShelf: "Trophy Shelf",
    trophiesCollected: "2 / 10 Collected",
    medalsCollection: "Medals Collection",
    medalsActive: "4 / 24 Active",
    history: "Event History",
    seeAll: "View all",
  },
  fr: {
    events: "Événements",
    wins: "Victoires",
    totalXp: "XP total",
    currentRank: "Rang Actuel",
    trophyShelf: "Étagère de trophées",
    trophiesCollected: "2 / 10 Collectés",
    medalsCollection: "Collection de médailles",
    medalsActive: "4 / 24 Actifs",
    history: "Historique des événements",
    seeAll: "Voir tout",
  },
} as const;
