export enum TypingStage {
  STAGE_1_HOME_ROW = "STAGE_1_HOME_ROW",
  STAGE_2_ROW = "STAGE_2_ROW",
  STAGE_3_WORD = "STAGE_3_WORD",
  STAGE_4_SENTENCE = "STAGE_4_SENTENCE",
  STAGE_5_PARAGRAPH = "STAGE_5_PARAGRAPH",
}
